server:
  port: 8710
spring:
  profiles:
    active: ${ENVIRONMENT:dev}
  application:
    name: shopoo-common
  cloud:
    nacos:
      username: ${NACOS_USERNAME}
      password: ${NACOS_PASSWORD}
      discovery:
        namespace: szmengran-${spring.profiles.active}
        server-addr: ${NACOS_SERVER_ADDRESS}
      config:
        namespace: szmengran-${spring.profiles.active}
        server-addr: ${NACOS_SERVER_ADDRESS}
  config:
    import:
      - nacos:knife4j.yaml
      - nacos:common.yaml
      - nacos:common-jdbc.yaml
      - nacos:common-redis.yaml
      - nacos:common-dubbo.yaml
      - nacos:common-rocketmq.yaml
      - nacos:common-oauth2-resource-server.yaml
      - nacos:shopoo-common.yaml